excerpt_separator: ""
pygments: rouge
markdown: kramdown
url: http://eduguideinsiders.github.io
title: EduGuide Insider
tagline: User Testing and Product development blog
description: Check here often for general announcements about new features, updates, and user testing opportunities.
paginate: 5
